# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Next Iteration
email: technopreneural@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to our user / organization page. We have a very diverse range of
  interests and an enormous appetite for the new, the obscure, and the alternate
  possibilities. Join us as we explore ideas, technologies, platforms,
  techniques, code, some of their potentially cool (ish) applications, and
  other possibilities.
baseurl: ""
url: "https://technopreneural.github.io"

# Build settings

# Menu pages --- anchor links to page sections
links:
    - title: Home
      url: /#test
    - title: Projects
      url: /#projects
    - title: About
      url: /#about
    - title: Contact
      url: /#contact
